import type { Metadata } from "next";
import "./ui/globals.css";
import ClientProviders from "./app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><ClientProviders>
        {children}
        </ClientProviders>
      </body>
    </html>
  );
}
