import type { Metadata } from "next";
import "./ui/globals.css";
import  ClientProviders  from "./app";
import Topbar from "./landing/components/Topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <title>Vite + React + TS</title>
      </head>
      <body>
<ClientProviders>
        {children}
        </ClientProviders>
      </body>
    </html>
  );
}
